### ISSUE TITLE
Negative new NAs

### ISSUE THREAD

**Issue by NickCH-K** [elbersb/tidylog#18]
Loving the package!

Very minor issue: when mutate is used to replace NA values with non-NA values, tidylog will report (-X new NA), where X is the number of values that were NA but no longer are.

It's still providing all the information it should, but the message is a little strange.

Example code:

    library(tidyverse)
    library(tidylog)
    df <- tibble(a = NA,
                     b = rnorm(100)) %>%
      mutate(a=ifelse(b<0,1,a))

**Comment by elbersb** [comment]
good catch! should be fixed now in the dev version - could you give it a try?

**Comment by NickCH-K** [comment]
Perfect! Thank you.
