### ISSUE TITLE
any chance the package messes up the computation/ objects in memory?

### ISSUE THREAD

**Issue by randomgambit** [elbersb/tidylog#19]
Hi,

This package is really a good idea. I just wonder, are there any possible weird side effects that can happen? Is the logging interfering with the dplyr computations at any point?

Thanks!

**Comment by elbersb** [comment]
The package just takes the inputs and forwards them to the respective `dplyr` functions, then returns the results. If you're asking whether the package is bug-free, I obviously can't give you a guarantee, but the functionality is simple enough that the room for possible bugs is small.
