### ISSUE TITLE
Interest in expanding this to other tidyverse packages?

### ISSUE THREAD

**Issue by WilDoane** [elbersb/tidylog#20]
Ben: love the approach. I've been focused on hacking on the pipe operator itself for far too long.

Before I go forking around with your package, I'm thinking of such things as tidyr and purrr. Feedback such as you provide for dplyr would be very helpful for spread, gather, map_df, etc...

Would you be open to such pull requests and expanding the scope of tidylog beyond just dplyr?

**Comment by elbersb** [comment]
sure, other functions would be great! It would probably be a good idea to briefly discuss here which functions you would add (maybe separate issues for separate functions/packages make sense), and with what kind of output. Overall, I'd restrict the package to functions that work on data frames, and that are part of the core data analysis workflow, loosely defined. So I think `gather` and `spread` would be great candidates, but functions from `purrr` seem a bit out of scope.

**Comment by elbersb** [comment]
I'll close this for now, feel free to open new issues for specific functions that are missing. Also see #22
