### ISSUE TITLE
add number of remaining rows

### ISSUE THREAD

**Issue by sahilseth** [elbersb/tidylog#23]
For a lazy person, who does not want to do the math :), is it possible to add the number of remaining rows in the data (in addition to the current numbers?)

What I often care about this the number of remaining 

```
filter: removed 287 out of 761 rows (38%), 474 remaining
filter: removed 230 out of 474 rows (49%), 244 remaining
```

Thanks!

**Comment by elbersb** [comment]
Yes, good point. I'm a bit hesitant to add another number, though. But maybe it's less important to see how many cases there were originally, and more interesting to see how many are left. So maybe switching to 

`r
filter: removed 287 rows (38%), 474 remaining
`

makes sense?

**Comment by sahilseth** [comment]
That would work well, I almost always do nrow after filter, joins etc, so this helps.
