### ISSUE TITLE
Report merge stats in joins (enhancement)

### ISSUE THREAD

**Issue by lpuettmann** [elbersb/tidylog#25]
Hey Benjamin,

Thanks for the cool package!

Wouldn't it be useful to report what share of rows have been dropped? 

So for this:

```r
x <- inner_join(band_members, band_instruments, by = "name")
```

show: 
`33% of left dataframe and 33% of right dataframe's rows dropped`.

I find that these joins are often a great source for bugs in my programs and it often has to do with losing many rows in the either left or right dataframe.

Best,
Lukas

**Comment by elbersb** [comment]
Hey,
right now, tidylog already reports this:

```r
x <- inner_join(band_members, band_instruments, by = "name")                
#> inner_join: removed one row and added one column (plays)
```

It's tricky to figure out how many rows are dropped from the "right" data frame, because then tidylog needs to figure out which rows have been merged, no? Of course it would be possible to add the percentage share of rows dropped to the left data frame.

**Comment by rubenarslan** [comment]
I'd be interested to see: 
rows in x not in y, rows in y not in x, rows in x and y (maybe as percentages of totals or also showing total number of rows), as well as number of duplicates for the `by` variables on each side.

I know this is much more extensive and verbose than what you have now, but my thinking goes that mistakes happen often enough that further logging would be very useful.

Some code [here](https://github.com/rubenarslan/rmdpartials/blob/master/R/join_sets.R)

**Comment by elbersb** [comment]
I started working on this on a new branch `joins`. If you have time, could you check it out?
Install via:
```r
devtools::install_github("elbersb/tidylog@joins")
```

Now the join commands print something like this:
```r
> tidylog::left_join(flights[1:10000, ], airlines[1:10, ], by = "carrier")
#>left_join: added one column (name)
#>           rows only in x    2,783
#>           rows only in y  (     0)
#>           matched rows      7,217
#>                           ========
#>           rows total       10,000
```

Any time a number is printed in parentheses, it means that those rows are not included in the result. For instance:

```r
> tidylog::anti_join(flights[1:100, ], airlines[1:10, ], by = "carrier")
#>anti_join: added no new columns
#>           rows only in x   34
#>           rows only in y  ( 3)
#>           matched rows    (66)
#>                           ====
#>           rows total       34
```

Not very well tested until now, so there will be issues...

**Comment by elbersb** [comment]
This is now on the main branch.
