### ISSUE TITLE
Include dplyr function rename in tidylog package

### ISSUE THREAD

**Issue by damianooldoni** [elbersb/tidylog#27]
While using this very useful package, I find it would be nice to get information also about column renaming while working with `dplyr::rename()` in pipes.

**Comment by elbersb** [comment]
This is a bit tricky because it’s impossible to tell how the columns were renamed from just inspecting the data frame before and after. This means one has to gather this information from the arguments, which is error-prone. Any ideas would be appreciated.

**Comment by damianooldoni** [comment]
> This is a bit tricky because it’s impossible to tell how the columns were renamed from just inspecting the data frame before and after.

Maybe by comparing column names by commando `colnames(df)` before and after? 

```r
> a <- data.frame(col1 = c(1,2), col2 = c(3,4))
> name_cols_before <- colnames(a)
> name_cols_before
[1] "col1" "col2"
> a <- dplyr::rename(a, newcol1 = col1)
> name_cols_after <- colnames(a)
> name_cols_after 
[1] "newcol1" "col2"
> paste(
  "Column", 
  name_cols_before[name_cols_after != name_cols_before], 
  "renamed as", 
  name_cols_after[name_cols_after != name_cols_before]
)
[1] "Column col1 renamed as newcol1"
```
This is for `dplyr::rename`, likely not for multiple renames via `rename_at` or `rename_if`.

Or did I misunderstand your reply? Still thanks for paying attention to this issue.

**Comment by elbersb** [comment]
Right, that's the approach that's being used for all the other functions. But I always assumed that `rename` would reorder the columns, which would make this strategy impossible. It seems though that rename does not reorder columns. This would mean all the column positions match up, and it shouldn't be a problem to implement `rename`, `rename_at`, `rename_all`, etc. Could you check whether this understanding is correct? The docs for dplyr don't mention this explicitly, so maybe we can experiment a bit more.

``` r
a <- data.frame(col1 = c(1,2), col2 = c(3,4))
names(a)
#> [1] "col1" "col2"
names(dplyr::rename(a, newcol1 = col1, newcol2 = col2))
#> [1] "newcol1" "newcol2"
names(dplyr::rename(a, newcol1 = col2, newcol2 = col1))
#> [1] "newcol2" "newcol1"
names(dplyr::rename(a, newcol2 = col2, newcol1 = col1))
#> [1] "newcol1" "newcol2"
```

<sup>Created on 2019-09-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by damianooldoni** [comment]
Thanks @elbersb : yes, I played a little with `rename_*` functions as well and no changes in order of columns detected.
