### ISSUE TITLE
Format large numbers

### ISSUE THREAD

**Issue by Moohan** [elbersb/tidylog#28]
For an output such as;
`filter: removed 7375373 out of 10541429 rows (70%)`
It would be nice for this to display as
`filter: removed 7,375,373 out of 10,541,429 rows (70%)`
to make reading easier, this would probably have to be locale dependant.

**Comment by elbersb** [comment]
yes, this would be nice. I'm trying to figure out the best way to implement this locale-dependent

**Comment by elbersb** [comment]
on the other hand, the rest of the output is in English as well, so commas are probably fine -- it's now implemented like that
