### ISSUE TITLE
Overwriting of nested columns not possible with tidylog::mutate

### ISSUE THREAD

**Issue by christianholland** [elbersb/tidylog#31]
When I overwrite a nested column with `mutate` it works with `dplyr::mutate()` but not with `tidylog::mutate()`

Check example below

```r
library(tidyverse)
library(tidylog)

# This doesn't work: Error in new != old : comparison of these types is not implemented
as_tibble(iris) %>% nest(-Species) %>% tidylog::mutate(data = data %>% map(function(data) {data$Sepal.Length + data$Sepal.Width}))

# This works
as_tibble(iris) %>% nest(-Species) %>% dplyr::mutate(data = data %>% map(function(data) {data$Sepal.Length + data$Sepal.Width}))
```

**Comment by elbersb** [comment]
Good catch! Hope I can get around to fixing it soon.

**Comment by elbersb** [comment]
This was a pretty straightforward fix. There might be other edge cases for list columns and other odd/rare columns types.

**Comment by christianholland** [comment]
Thanks for the fix and the development of this great package in general!
