### ISSUE TITLE
Renaming while selecting gives confusing message.

### ISSUE THREAD

**Issue by frederikziebell** [elbersb/tidylog#35]
The code
```
tibble(x=1,y=2,z=3) %>% 
  select(a=x,b=y)
```
results in `select: dropped 3 variables (x, y, z)`. While technically true, I would rather call it "renamed 2 variables, dropped 1 variable".

**Comment by elbersb** [comment]
Yes, good point. I'll take a look in the coming days.

**Comment by elbersb** [comment]
The select command should now handle all possible cases:

- renaming and dropping of variables
- renaming of some variables only
- dropping of some variables only
- column reordering only
- no changes at all

Please test to see if I covered all edge cases.
