### ISSUE TITLE
Function masking workaround

### ISSUE THREAD

**Issue by TylerGrantSmith** [elbersb/tidylog#36]
I saw your post on Twitter about version 1.0.0 and I wanted to thank you for your work on this package!  Inspired by one of the comments that expressed concern about overloading the `dplyr` and `tidylog` functions, I started work on a package, https://github.com/TylerGrantSmith/mask, that would allow you to use `tidylog` without loading it into the search path.

It is still just an early concept, but I wanted to get your opinion on functionality.

Here is an example reprex:
``` r
library(magrittr)

# clean searchpath
searchpaths()
#>  [1] ".GlobalEnv"                                            
#>  [2] "C:/Users/e014307/Documents/R/R-3.6.2/library/magrittr" 
#>  [3] "C:/Users/e014307/Documents/R/R-3.6.2/library/stats"    
#>  [4] "C:/Users/e014307/Documents/R/R-3.6.2/library/graphics" 
#>  [5] "C:/Users/e014307/Documents/R/R-3.6.2/library/grDevices"
#>  [6] "C:/Users/e014307/Documents/R/R-3.6.2/library/utils"    
#>  [7] "C:/Users/e014307/Documents/R/R-3.6.2/library/datasets" 
#>  [8] "C:/Users/e014307/Documents/R/R-3.6.2/library/methods"  
#>  [9] "Autoloads"                                             
#> [10] "tools:callr"                                           
#> [11] "C:/Users/e014307/DOCUME~1/R/R-36~1.2/library/base"

# mask expressions
mask::tidylog_mask(mtcars %>% 
  dplyr::select(mpg, cyl) %>% 
  dplyr::filter(mpg < 15) %>% 
  dplyr::group_by(cyl) %>%
  dplyr::summarise(mean = mean(mpg)))
#> select: dropped 9 variables (disp, hp, drat, wt, qsec, …)
#> filter: removed 27 rows (84%), 5 rows remaining
#> group_by: one grouping variable (cyl)
#> summarise: now one row and 2 columns, ungrouped
#> # A tibble: 1 x 2
#>     cyl  mean
#>   <dbl> <dbl>
#> 1     8  12.6

# mask individual functions
select <- mask::tidylog_mask(dplyr::select)
mtcars %>% 
  select(mpg, cyl) %>% 
  dplyr::filter(mpg < 15)
#> select: dropped 9 variables (disp, hp, drat, wt, qsec, …)
#>    mpg cyl
#> 1 14.3   8
#> 2 10.4   8
#> 3 10.4   8
#> 4 14.7   8
#> 5 13.3   8
```
<sup>Created on 2020-01-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

  In addition, there is an RStudio addin that allows you to run selected code with `tidylog` using a keybinding.

**Comment by elbersb** [comment]
Hi,
it looks like this approach would require extra work (i.e., masking all function calls) to make tidylog work. The appeal to me (and many others, it seems), was always that it is a drop-in solution. I personally do not have a problem with the overloading, and I also don't understand the concern that is expressed in the tweet (unfortunately the person has not responded). Of course, tidylog introduces another layer, and this might be a source of bugs, as any additional package will be. But the masking approach won't really change this, won't it?

**Comment by DougManuel** [comment]
Could someone post a link to the tweet or elaborate on the discussion?

**Comment by TylerGrantSmith** [comment]
@elbersb  I do not personally have a problem with the overloading either, but there are situations where I would want the `tidylog` functionality and the current form would not make that possible.  

For example, I often explicitly scope my `dplyr` calls using `dplyr::`, which would bypass `tidylog`.  I wouldn't want to have to rewrite my scripts to get `tidylog` to work.  As another example, what if I wanted to incorporate this functionality into a package, where it is much more likely that I have `dplyr`/`tidyr` verbs explicitly scoped.  That is mostly what I was trying to address with `mask`, by inserting `tidylog` into the search path of the execution, and intercepting calls to `::` and `:::` to allow `tidylog` to handle them before passing to their respective namespaces.

@DougManuel  the tweet was https://twitter.com/carlmcqueen/status/1214558150793150466

**Comment by maciejmotyka** [comment]
> For example, I often explicitly scope my `dplyr` calls using `dplyr::`, which would bypass `tidylog`. I wouldn't want to have to rewrite my scripts to get `tidylog` to work. As another example, what if I wanted to incorporate this functionality into a package, where it is much more likely that I have `dplyr`/`tidyr` verbs explicitly scoped.

Yes, yes! I very often switch between `tidylog::` and `dplyr::`, based on whether I need the info or not. I'd very much appreciate any way to make the switch easier, be it via `tidylog` itself or `mask`.
Maybe the masking could be turned on/off by specifying an option, e.g. `tidylog_mask(your_code_here, mask = T|F)`

**Comment by elbersb** [comment]
> For example, I often explicitly scope my `dplyr` calls using `dplyr::`, which would bypass `tidylog`. I wouldn't want to have to rewrite my scripts to get `tidylog` to work.

I see how this is a use case. But it would still require changing the script in the sense that you either have to insert a code block with all the functions that you want to mask, or mask those statements where you want a log, right? There is already a section in the README about the [conflicted](https://cran.r-project.org/web/packages/conflicted/index.html) package, which solves a somewhat similar problem. If you'd like, I'm happy to add something about the masking approach too.

> Yes, yes! I very often switch between tidylog:: and dplyr::, based on whether I need the info or not. I'd very much appreciate any way to make the switch easier, be it via tidylog itself or mask.
Maybe the masking could be turned on/off by specifying an option, e.g. tidylog_mask(your_code_here, mask = T|F)

This also sounds like something the [conflicted](https://cran.r-project.org/web/packages/conflicted/index.html) package is designed to solve. Of course, this requires not to use any package prefixes, but if that's the case, then the switching is very easy.

**Comment by saadaslam** [comment]
Adding on to this -

I think the idea behind this package is great, but the conflicts issue seems somewhat untidy. I'm wondering if a more reasonable approach would be to create a S3 object (say, `tidylog_df`) and rewrite the functions as S3 methods. `dplyr` and `tidyr` use S3 methods for the most part.

**Comment by elbersb** [comment]
> I think the idea behind this package is great, but the conflicts issue seems somewhat untidy. I'm wondering if a more reasonable approach would be to create a S3 object (say, `tidylog_df`) and rewrite the functions as S3 methods. `dplyr` and `tidyr` use S3 methods for the most part.

If I understand your proposal correctly, this would suffer from the same problem: tidylog would no longer be a drop-in solution, but you would have to change your dataframes/tibbles to tidylog_df's (or similar).

**Comment by elbersb** [comment]
I'm going to close this issue now, but feel free to reopen if there are new ideas.

@TylerGrantSmith If you consider your package production-ready, I'm happy to link to it in the README (similar to the `conflicted` package).
