### ISSUE TITLE
Mutating column to date

### ISSUE THREAD

**Issue by fogartjo** [elbersb/tidylog#38]
Maybe it's intentional, but shouldn't this say "Date" and not "double"?

``` r
data.frame(x = c("2016-01-01", "2016-01-02")) %>% 
  tidylog::mutate(x = as.Date(x))
#> mutate: converted 'x' from factor to double (0 new NA)
#>            x
#> 1 2016-01-01
#> 2 2016-01-02
```

**Comment by TylerGrantSmith** [comment]
This is correct in the sense that `typeof(as.Date("2016-01-01"))` is `"double"`.  Though I suppose you saying that it should be reporting the class of the column, `"Date"` and not the type?

**Comment by elbersb** [comment]
I agree that this should get changed. This is similar to the case of `factor` variables, whose type is `integer`, but of course tidylog should report them as factors. I'll fix this.

**Comment by fogartjo** [comment]
Thanks! I appreciate the package - it's already saved me a few headaches. Sorry for the nitpicky issue

**Comment by elbersb** [comment]
not nitpicky at all -- would've certainly stumbled upon that myself eventually
