### ISSUE TITLE
Explicit messages even when no changes result

### ISSUE THREAD

**Issue by TylerGrantSmith** [elbersb/tidylog#39]
I'm not sure I have a strong opinion about it, but I would like to hear others about the following example  `mtcars %>% select(hp, everything())`.  `tidylog` produces no message because nothing really changed except the column order, but I still think it should produce a notification like `select: no variables were dropped` consistent with how `filter` works when currently when no rows are dropped.

**Comment by maciejmotyka** [comment]
So maybe: `select: changed column order`?

**Comment by elbersb** [comment]
Yes, the change in column order should be reported. More generally, I think every call should produce a message.Should also check the other commands to see if that's the case.

**Comment by elbersb** [comment]
The select command should now handle all possible cases:

- renaming and dropping of variables
- renaming of some variables only
- dropping of some variables only
- column reordering only
- no changes at all

Please test to see if I covered all edge cases.
