### ISSUE TITLE
tidylog output in html markdown

### ISSUE THREAD

**Issue by akarlinsky** [elbersb/tidylog#40]
I'm creating an HTML document with R-Markdown. The resulting file includes all the messages from tidylog. Is there an option to turn these off in html/output mode?

**Comment by elbersb** [comment]
You could set a custom function so that tidylog only prints messages when you use it interactively.

```r
library("tidylog", warn.conflicts = FALSE)
custom_message <- function(m) {
  if(interactive()) message(m)
}
options("tidylog.display" = list(custom_message))
```

**Comment by akarlinsky** [comment]
I think the issue can be closed now. Thanks!
