### ISSUE TITLE
Hints in the autocomplete

### ISSUE THREAD

**Issue by crotman** [elbersb/tidylog#44]
I love tidylog, but a caveat is that we don't have the same hints about the parameters, when you are coding and hit ctrl+space, for instance, that you have when you use the original tidyverse packages.

Do you plan to improve this?

**Comment by elbersb** [comment]
is this a feature of RStudio? I don't think there is a way to improve this, really. The only solution would be to copy the whole function signatures from dplyr/tidyr, but that's messy and will lead to a lot of maintenance issues.

**Comment by crotman** [comment]
Yes, when you click ctrl+space you can see hints about the parameters.

I'll think about a good solution and suggest if I come up with one.

![tela](https://user-images.githubusercontent.com/26494490/76113650-4c349f80-5fc3-11ea-8d4f-588f4b310458.png)

**Comment by elbersb** [comment]
I've been playing around with this, but haven't found a good solution. I'm not a heavy user of RStudio myself, so I'm unable to provide much help.
Maybe this thread is of interest too: https://github.com/elbersb/tidylog/issues/36

**Comment by crotman** [comment]
I'm using the following strategy: I do not load tidylog using "library". When I want to take a look at logs I use tidylog::inner_join() or any other function I want to use. So I'm closing this issue
