### ISSUE TITLE
log for bind_*() functions

### ISSUE THREAD

**Issue by damianooldoni** [elbersb/tidylog#49]
Hi @elbersb!
Have you ever considered to implement logs for dplyr functions `bind_rows()` and `bind_cols()`?
I am using them in pipes in combination with other dplyr functions and it seems the pipe instructions didn't work as expected, although it is just a missing step in the log. What do you think about it?

**Comment by elbersb** [comment]
I consider the bind_* function out of scope for tidylog because they don't operate on data frames. They operate on lists, which no other functions currently covered by tidylog do. I'm also wondering what kind of message would be useful. What were you thinking?

**Comment by elbersb** [comment]
Something like "bind_cols: combined X data frames into a data frame with Y columns and Z rows"?

**Comment by elbersb** [comment]
Closing as out of scope.
