### ISSUE TITLE
Making output optional

### ISSUE THREAD

**Issue by neuwirthe** [elbersb/tidylog#5]
I think I really could use this in my classes for demos.
But I would prefer to habe an option to switch the additional output on and off.
Can this be done (or added)?

**Comment by elbersb** [comment]
There is now a way to do this by setting a global option:

```r
options("tidylog.display" = list())  # turn off
a <- filter(mtcars, mpg > 20)

options("tidylog.display" = NULL)    # turn on
a <- filter(mtcars, mpg > 20)
#> filter: removed 18 rows (56%)
```

See the README for more information.
