### ISSUE TITLE
Make ungroup log message more explicit

### ISSUE THREAD

**Issue by SimonDedman** [elbersb/tidylog#50]
Hi folks, firstly: I LOVE this package, it's so helpful!

Small one, relating to #32 : ungrouping a grouped object tells you:

`df %<>% ungroup`

> ungroup: no grouping variables

Which (IMHO) is unclear/ambiguous as to whether the input object HAD no grouping variables to begin with (i.e. "ungroup didn't have anything to do"), or if it HAS no grouping variables NOW, thanks to the ungroup call (i.e. "ungrouped successfully").

Maybe:

> ungroup: previously grouped by ID [count], now ungrouped

?

Cheers!

**Comment by elbersb** [comment]
Can you give one or two examples of situations in which this would be useful? I'm always hesitant of adding more output, because the noise to signal ratio of the logs is already not very high for certain operations.

**Comment by SimonDedman** [comment]
Hi Ben,

I guess all situations, honestly. As it stands, the message means "no grouping variables remain" so I guess the easiest change would simply be adding the "remain" to make it explicitly clear that the message refers to the output state not the input state. Of additional interest would be to confirm what the input state was, e.g. by using the grouping info message provided when you view a tibble df, and then appending the existing message, i.e.

> ungroup: previously grouped by ID [count]. no grouping variables remain

**Comment by elbersb** [comment]
Sorry for the slow response, lots of things going on here.

I see your point now, and have added "remain" to the message (see https://github.com/elbersb/tidylog/commit/902edc11f1895f36c63404687f3da9458382917b).

About the input state, I'm less sure. If you call ungroup, would it really matter what the grouping variables were before?

**Comment by SimonDedman** [comment]
No worries fella.

My thinking is that telling the user about the prior grouping variables (or lack thereof) informs them about the state of the object entering the pipe, confirming the need (or lack thereof) to do this operation. Certainly from my own work I've come back to code snippets and the outputs have changed because the input object has been saved with grouping variables left attached. Naturally the rebuttal to this is "don't commit bad practices"... I guess I'm thinking it wouldn't hurt to be given a check/confirmation at this stage, rather than having the task being done (or not) by ungroup be opaque. On the one hand, this isn't strictly necessary, OTOH that seems kinda the point of this wonderful package - to provide a bit more info than is strictly necessary, to better inform the user.

Your call either way obviously! Cheers.

**Comment by elbersb** [comment]
Closing this for now. I feel like the package is already quite noisy, and I think in most cases this information is not needed.
