### ISSUE TITLE
Mutate doesn't work with set_units()

### ISSUE THREAD

**Issue by vorpalvorpal** [elbersb/tidylog#51]
The title says it all. See code below. Also, thanks for the great package. You have no idea how frustrating debugging pipes had been as a newbie until I discovered tidylog :)

```
library(tidyverse)
library(units)

df <- tribble(~A, ~B,
        1, 2,
        2, 3)

df %>%
  mutate(B = set_units(B , mg)) %>%
  print()
# A tibble: 2 x 2

library(tidylog)

df %>%
  mutate(B = set_units(B , mg)) %>%
  print() 
# Error in Ops.units(new, old) : 
#  both operands of the expression should be "units" objects
```

**Comment by elbersb** [comment]
Thanks for opening the issue. I don't use the units package, so it might be a bit until I get to this.

**Comment by elbersb** [comment]
Should work now!
