### ISSUE TITLE
Can `tidylog::filter` also report the number of groups

### ISSUE THREAD

**Issue by statzhero** [elbersb/tidylog#52]
Hope this is a simple questions: can `tidylog::filter` also report the number of groups? Or what would be a workaround?

For example, current 
`filter (grouped): removed 78,720 rows (40%), 118,956 rows remaining`
and desired
`filter (grouped): removed 78,720 rows (40%), 118,956 rows remaining; removed 100 groups (10%), 900 groups remaining`

**Comment by elbersb** [comment]
Yes, that would be a nice addition. Will probably be a while before I get to this.

**Comment by statzhero** [comment]
Thank you - I will issue a PR if I get to it.

**Comment by statzhero** [comment]
FYI: I hacked myself something together with ` n_groups <- dplyr::n_groups(.data) - dplyr::n_groups(newdata)` but alas it's not solid enough for a PR.

**Comment by elbersb** [comment]
This should work now:

``` r
library(dplyr)
gb <- group_by(mtcars, gear)
out <- tidylog::filter(gb, am == 0)
#> filter (grouped): removed 13 rows (41%), 19 rows remaining (removed one group, 2 groups remaining)
```

<sup>Created on 2022-01-30 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by elbersb** [comment]
yes this is probably the effect of this #41
