### ISSUE TITLE
Tidylog function masking using `...` means RStudio auto-complete and function definition help is not available.

### ISSUE THREAD

**Issue by orgadish** [elbersb/tidylog#56]
`tidylog` has been hugely helpful for me in my data analysis workflows (thank you!). However, its masking of `tidyr` and `dplyr` functions using `...` notation means that I can no longer use RStudio auto-complete for function arguments, or hover over the function name to see the arguments.

I used to use this all the time with `pivot_wider` and `pivot_longer` where I always forget `names_to` vs `names_from`, for example. Now in order to do this I have to explicitly type `tidyr::pivot_wider(` to start the autocomplete or search for the help.

Is there a way to perform the masking without replacing the help functionality?

**Comment by elbersb** [comment]
This came up before: #44. Unfortunately, I don't think there is a good solution for this. Tidylog could copy over the complete function signature from dplyr/tidyr, but that would be a nightmare to maintain.

**Comment by orgadish** [comment]
What would you think about copying the signature specifically for `pivot_wider` and `pivot_longer` as I think those are the ones which I would use the most. I would happily submit the PR for that (should be trivial).

**Comment by elbersb** [comment]
The problem with that approach is that if the signature of these functions ever changes, then the tidylog signature might be different from the signature that is actually in the function - and that would be a big mess. So unfortunately I still don't really have a good idea of how to solve this.

**Comment by orgadish** [comment]
@elbersb I've proposed a feature rstudio/rstudio#16069 which would help resolve this.

I agree with you the this should be handled in a more general manner than something specific to tidylog.

**Comment by orgadish** [comment]
@elbersb If it gets accepted, rstudio/rstudio#17149 will add autocompletion when using roxygen2's `@inheritDotParams` tag. That would mean the only change to `tidylog` is to the documentation generation.

**Comment by orgadish** [comment]
@elbersb Success! rstudio/rstudio#17149 has now merged.

If we use roxygen2's `@inheritDotParams`, it will build a help Rd that includes the inherited params based on the version of tidyverse installed at the time of generating the documentation. This means that someone using an older/newer version of the packages would have incorrect documentation and autocomplete, which is not great, but crucially, would not be broken like we were discussing on #77 (unless they tried using an autocomplete that didn't exist). We could always just add that note to the documentation that the inherited params are based on version XXX and that other versions may have different inherited params.

What do you think?

**Comment by elbersb** [comment]
Great work! 

Just for my understanding: Aren't the autocompletions fetched at runtime from the package that the user has installed? If yes, why would there ever be a mismatch? I thought with this change we'd just need to add `@inheritDotParams` and the Rd files would not pull in the actual arguments.

**Comment by orgadish** [comment]
Unfortunately, it doesn't pull at runtime, it pulls from the Rd file. The way that `@inheritDotParams` works currently, it's just an indication for `roxygen2` of how to build the Rd file. It populates the "inherited" parameters under the `...`, like this in `ggplot2::scale_color_grey` which inherits from `discrete_scale`:
<img width="953" height="556" alt="Image" src="https://github.com/user-attachments/assets/1fa98cfd-e0ff-4c8e-9320-a42119653ed9" />

rstudio/rstudio#17149 processes Rd help files that use this specific structure to enhance autocompletion to include those inherited arguments, resulting in something like this:
<img width="475" height="256" alt="Image" src="https://github.com/user-attachments/assets/004c84a0-36e0-4177-8598-714283c0ee8d" />

To take advantage of that same process in this package, we would have to use roxygen to write the Rd files or create the Rd files using this exact structure directly. Either way, all it's doing is pulling the information from the Rd file, not doing any real-time lookup.

So there would still be the limitation of a disconnect between the installed version and the documentation version. However, it would not break at runtime like in #77.

**Comment by elbersb** [comment]
I see, let's do it then. We should document in a few places that the installed version might diverge from the version that was used to build then docs. Probably we should also make sure that the package is always built with a recent version of dplyr/tidyr?

**Comment by orgadish** [comment]
I've updated #77 to still use dynamic build-time generation of the wrappers, but only use `.data, ...` signatures and rely on roxygen to form the documentation.

I have not yet added a check to make sure that the package is built with a recent version of dplyr/tidyr. What do you think is the best way to do that? Check that it's built with the latest dplyr/tidyr, or just that it isn't built with something older than what already existed?

Note: I have added to each documentation a `@details` section that indicates which version it was built with.

**Comment by elbersb** [comment]
Closed by #77

**Comment by moritzpschwarz** [comment]
It's super cool that this has been implemented on the main branch - may I ask when this might be up on CRAN?
