### ISSUE TITLE
Can/Should tidylog::filter throw a message or warning on 'missing' filter group?

### ISSUE THREAD

**Issue by daranzolin** [elbersb/tidylog#57]
Suppose I want to filter some data for three groups ('A', 'B', 'C'). I assume the presence of all three, but my data for whatever reason only has 'A' and 'B' and 'D'. It would be useful to receive immediate feedback that part of my filter wasn't there (maybe because of a typo or other data pipeline reasons). A warning might be too strong, but a message as part of the tidylog message maybe? See the reprex below. 

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
suppressPackageStartupMessages(library(tidylog))

df <- data.frame(
  x = sample(c("A", "B", "D"), 10, replace = TRUE),
  y = rnorm(10)
)

df %>% 
  filter(x %in% c("A", "B", "C")) %>% # Warning that there are no 'C' rows?
  summarize(my = mean(y))
#> filter: removed 2 rows (20%), 8 rows remaining
#> summarize: now one row and one column, ungrouped
#>           my
#> 1 -0.2840769
```

<sup>Created on 2022-01-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by elbersb** [comment]
Hi, unfortunately, tidylog cannot parse this information. The `filter` conditions can be much more complex (e.g., `x %in% c("A", "B", "C") & a %in% c("X", "Y")`, or a regular expression, or anything else that generates a logical vector). 

For the use case you describe, maybe a join is more informative? The output below would show you that something is wrong: Some rows in x are dropped, and one row from y doesn't exist in x.

``` r
library(dplyr)
suppressPackageStartupMessages(library(tidylog))

df <- data.frame(
  x = sample(c("A", "B", "D"), 10, replace = TRUE),
  y = rnorm(10)
)

inner_join(df, tibble(x = c("A", "B", "C")))
#> Joining, by = "x"
#> inner_join: added no columns
#>             > rows only in x  (4)
#>             > rows only in y  (1)
#>             > matched rows     6
#>             >                 ===
#>             > rows total       6
#>   x          y
#> 1 A -0.8780702
#> 2 A  0.3984208
#> 3 B  0.4299541
#> 4 B  1.4819892
#> 5 B  0.7412264
#> 6 B  2.5109785
```

<sup>Created on 2022-01-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
