### ISSUE TITLE
Date support

### ISSUE THREAD

**Issue by arrismo** [elbersb/tidylog#69]
Hi @elbersb !
My team and I are big fans of this package and would like to build a dates version of this package. For example, providing feedback from packages like [lubridate](https://lubridate.tidyverse.org/). Any specific guidelines on how to cite the `tidylog` package?

Thank you for considering!

**Comment by elbersb** [comment]
hi! you don't need to do anything special, just a link would be nice

**Comment by arrismo** [comment]
Great, thanks!
